name: Run Python 1M

on:
  schedule:
    - cron: '0 21 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
    
    - name: Install dependencies
      run: |
        pip install openbb tradingview-screener numpy pandas requests
    
    - name: List files for debugging
      run: ls -R
    
    - name: Debug Python environment
      run: |
        python --version
        python -m pip list
    
    - name: Run script
      run: python alex_1M.py
